# Generated by Django 4.1.2 on 2023-03-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_remove_properfeedback_feed_polarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='pymentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_created=True, auto_now=True)),
                ('user', models.CharField(max_length=50)),
                ('Owner', models.CharField(max_length=50)),
                ('prop_name', models.CharField(max_length=50)),
                ('PaymentVia', models.CharField(max_length=50)),
                ('PaymentMethod', models.CharField(max_length=50)),
                ('Amount', models.CharField(max_length=50)),
                ('transactionId', models.TextField(default=None)),
            ],
        ),
    ]
