# Generated by Django 4.1.2 on 2023-03-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_pymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pyment',
            field=models.BooleanField(default=False),
        ),
    ]
